### ISSUE TITLE
This module not import

### ISSUE THREAD

**Issue by deivisonmoraes** [saeed-sb/fixboproductname#1]
I tried to install this module to solve the names problem but prestashop does not accept it as a valid module. Version 1.7.

**Comment by saeed-sb** [comment]
Hi,

for solve the problem, after download, open the zip file and remove "-master" from the end of folder name.

**Comment by deivisonmoraes** [comment]
Tks. Solved problem!

**Comment by fercaldas** [comment]
Friend,

After install this module, all modules that I have in standard sections in my "Module Manager" (as Administration, Design&navigation, Promotions, etc) was moved to "Others"
![image](https://user-images.githubusercontent.com/56198163/78706192-ac797280-78dc-11ea-9dad-c60102f8d1a3.png)

Anyway to fix that?

**Comment by fbsoft** [comment]
It worked like a charm. I had to let it finish, to be able to open, as there was a limit to the server no of handles. thank you.
@fercaldas after a refresh, it was ok for me, i had no cache or anything on when i ran it, try to clear the cache

**Comment by nishanthr93** [comment]
Thanks, Dude This Module Helps .
